/**
 * 포스트 슬러그 일괄 변경(2026.05)에 따른 301 리다이렉트 매핑.
 *
 * - prod published 슬러그와 교차검증 완료(총 110건, self-loop 1건 제외).
 * - from: 변경 전 슬러그 / to: 변경 후 슬러그 (둘 다 /posts/ 경로 제외, 슬러그만).
 * - next.config.ts의 redirects()에서 import하여 301(permanent) 리다이렉트로 사용.
 *
 * ⚠️ 이 매핑은 검증된 데이터다. 임의로 수정/추가/삭제하지 말 것.
 *    신규 슬러그 변경 발생 시에만 항목을 추가한다.
 */

export interface PostSlugRedirect {
    /** 변경 전 슬러그 (예: army-bomb-holy-ground-...) */
    from: string;
    /** 변경 후 슬러그 (예: kpop-bts-concert-...-recree) */
    to: string;
  }
  
  export const POST_SLUG_REDIRECTS: PostSlugRedirect[] = [
    { from: "army-bomb-holy-ground-where-btss-legend-was-forged", to: "kpop-bts-concert-filming-location-jamsil-olympic-stadium-songpa-recree" },
    { from: "bts-rms-pick-cafe-onion-anguk-an-atmospheric-hanok-cafe", to: "kpop-bts-rm-cafe-photo-location-onion-anguk-jongno-recree" },
    { from: "the-cafe-where-bts-v-shot-his-solo-album-concept-photos", to: "kpop-bts-v-layover-photo-location-midopa-cafe-seodaemun-recree" },
    { from: "bts-gangnamdol-the-exact-spot-where-the-members-themselves-took-photos", to: "kpop-bts-gangnamdol-photo-location-kstar-road-gangnam-recree" },
    { from: "bts-permission-to-dance-butter-live-performance-venue-sungnyemun", to: "kpop-bts-global-citizen-live-filming-location-sungnyemun-junggu-recree" },
    { from: "gyeongbokgungs-geunjeongjeon-hall-bts-idol-stage", to: "kpop-bts-idol-performance-filming-location-gyeongbokgung-jongno-recree" },
    { from: "art-for-life-the-atmospheric-cafe-rm-visited-on-the-eve-of-his-enlistment", to: "kpop-bts-rm-enlistment-eve-cafe-art-for-life-jongno-recree" },
    { from: "rms-famous-kimdaily-carousel-photo-spot", to: "kpop-bts-rm-kimdaily-carousel-photo-location-lotte-world-songpa-recree" },
    { from: "btss-speed-quiz-mission-viking-ride-from-run-bts-episode-50-special", to: "kpop-bts-run-bts-ep50-filming-location-lotte-world-viking-songpa-recree" },
    { from: "btss-regular-spot-right-above-their-practice-room-yujeong-sikdang", to: "kpop-bts-trainee-regular-restaurant-yujeong-sikdang-gangnam-recree" },
    { from: "jin-had-jjamppong-v-added-chili-powder-to-his-jajangmyeon-the-chinese-restaurant-whose-flavors-havent-changed", to: "kpop-bts-jin-v-run-bts-restaurant-geumhong-gangnam-recree" },
    { from: "the-park-where-bts-trainees-shared-dreams-and-worries-on-swings", to: "kpop-bts-trainee-practice-visited-spot-hakdong-park-gangnam-recree" },
    { from: "the-alleyway-where-rm-and-v-were-caught-eating-ice-cream-during-their-trainee-days-and-hastily-hid-it", to: "kpop-bts-rm-v-trainee-ice-cream-photo-location-second-dorm-gangnam-recree" },
    { from: "insta-perfect-convenience-store-with-n-seoul-tower-view", to: "korea-seoul-namsan-tower-view-photo-spot-jongno-recree" },
    { from: "bts-mikrokosmos-stage-gyeonghoeru-pavilion-gyeongbokgung-palace", to: "kpop-bts-mikrokosmos-tonight-show-filming-location-gyeonghoeru-jongno-recree" },
    { from: "that-bridge-where-butter-was-danced-the-bts-world-cup-bridge", to: "kpop-bts-butter-tonight-show-filming-location-worldcup-bridge-mapo-recree" },
    { from: "bts-10th-anniversary-a-moving-purple-spectacle-at-yeouido-hangang-park", to: "kpop-bts-10th-anniversary-festa-filming-location-yeouido-hangang-yeongdeungpo-recree" },
    { from: "rm-and-jimins-nostalgic-path-the-road-bts-members-walked-every-day-as-trainees", to: "kpop-bts-rm-jimin-trainee-daily-path-photo-location-nonhyeon-gangnam-recree" },
    { from: "btss-second-dorm-memories-of-the-blue-house", to: "kpop-bts-second-dorm-blue-house-visited-spot-nonhyeon-gangnam-recree" },
    { from: "btss-fourth-dorm-cafe-hyuga-an-army-pilgrimage-site", to: "kpop-bts-fourth-dorm-cafe-hyuga-visited-spot-hakdong-gangnam-recree" },
    { from: "nodeul-island-the-sprint-from-btss-run-mv", to: "kpop-bts-run-mv-filming-location-nodeul-island-yongsan-recree" },
    { from: "national-museum-of-korea-site-of-btss-three-song-performance", to: "kpop-bts-dear-class-2020-filming-location-national-museum-yongsan-recree" },
    { from: "big-hits-former-hq-imbued-with-btss-sweat-and-dreams", to: "kpop-bts-trainee-practice-room-bighit-old-hq-gangnam-recree" },
    { from: "btss-first-dorm-a-place-full-of-cherished-memories", to: "kpop-bts-first-dorm-trainee-visited-spot-nonhyeon-gangnam-recree" },
    { from: "jungkooks-first-destination-on-run-bts-the-most-fun-place-with-the-members", to: "kpop-bts-jungkook-run-bts-telepathy-visited-spot-lotte-world-songpa-recree" },
    { from: "night-ride-on-the-han-river-just-like-j-hope", to: "kpop-bts-jhope-instagram-night-cycling-photo-location-hangang-park-recree" },
    { from: "the-namsan-view-pedestrian-overpass-captured-by-bts-j-hope", to: "kpop-bts-jhope-instagram-namsan-view-photo-location-overpass-recree" },
    { from: "dongjak-bridge-where-v-took-his-iconic-love-yourself-poster-photo", to: "kpop-bts-v-love-yourself-poster-photo-location-dongjak-bridge-dongjak-recree" },
    { from: "bts-skool-luv-affair-concept-photo-shoot-location", to: "kpop-bts-skool-luv-affair-concept-photo-location-graffiti-wall-recree" },
    { from: "vs-convenience-store-the-highlight-reel-spot", to: "kpop-bts-v-highlight-reel-filming-location-7eleven-hannam-yongsan-recree" },
    { from: "bts-run-mv-lets-run-like-the-members", to: "kpop-bts-run-mv-filming-location-hangang-seobinggo-yongsan-recree" },
    { from: "gaemi-village-from-bts-jungkooks-love-yourself-poster", to: "kpop-bts-jungkook-love-yourself-poster-photo-location-gaemi-village-seodaemun-recree" },
    { from: "a-sentimental-pilgrimage-to-btss-spring-day-bus-stop", to: "kpop-bts-spring-day-album-jacket-photo-location-jumunjin-beach-gangneung-recree" },
    { from: "hikr-ground-seouls-ultimate-k-culture-playground", to: "korea-seoul-kpop-mv-experience-hikr-ground-jongno-recree" },
    { from: "full-of-k-vibe-seouls-insadong-traditional-street", to: "korea-seoul-insadong-traditional-street-landmark-jongno-recree" },
    { from: "bukchon-hanok-village-immerse-yourself-in-k-drama-vibes", to: "korea-seoul-bukchon-hanok-village-photo-spot-jongno-recree" },
    { from: "seouls-first-permanent-market-120-years-old-a-mecca-for-bindaetteok-and-yukhoe", to: "korea-food-seoul-gwangjang-market-street-food-jongno-recree" },
    { from: "the-heart-of-k-culture-hongdae-a-street-pulsating-with-youthful-energy", to: "korea-spot-seoul-hongdae-youth-culture-landmark-mapo-recree" },
    { from: "the-iconic-tower-from-k-dramas-a-symbol-of-romantic-seoul", to: "korea-spot-seoul-namsan-tower-landmark-yongsan-recree" },
    { from: "insaengnecut-your-ultimate-korean-instant-photo-booth-experience", to: "korea-spot-seoul-insaengnecut-photo-booth-recree" },
    { from: "the-path-from-k-dramas-naksan-parks-fortress-wall-night-view", to: "korea-spot-seoul-naksan-park-fortress-wall-viewpoint-jongno-recree" },
    { from: "discovering-the-roots-of-k-culture", to: "korea-spot-seoul-national-museum-landmark-yongsan-recree" },
    { from: "ddp-seouls-alluring-cultural-complex", to: "korea-spot-seoul-dongdaemun-design-plaza-ddp-landmark-jung-recree" },
    { from: "full-of-k-vibe-a-stroll-through-ikseon-dong-hanok-alley", to: "korea-spot-seoul-ikseon-dong-hanok-village-photo-spot-jongno-recree" },
    { from: "picnic-at-mangwon-hangang-park-your-han-river-escape-next-to-hongdae", to: "korea-spot-seoul-mangwon-hangang-park-picnic-mapo-recree" },
    { from: "changgyeonggung-palace-step-into-a-historical-drama", to: "korea-spot-seoul-changgyeonggung-palace-landmark-jongno-recree" },
    { from: "the-last-imperial-palace-of-the-korean-empire-where-hanok-and-western-buildings-coexist", to: "korea-spot-seoul-deoksugung-palace-landmark-jung-recree" },
    { from: "that-palace-from-k-dramas-your-ultimate-hanbok-photo-spot", to: "korea-spot-seoul-gyeongbokgung-palace-hanbok-photo-spot-jongno-recree" },
    { from: "squid-game-2-the-recruiters-appearance-at-seouls-first-modern-park", to: "kdrama-squid-game-season-2-recruiter-filming-location-tapgol-park-jongno-recree" },
    { from: "queen-of-tears-hae-in-hyun-woos-railbike-date", to: "kdrama-queen-of-tears-railbike-date-filming-location-gurangri-mungyeong-recree" },
    { from: "the-glory-dong-eun-and-yeo-jeongs-iconic-go-game-spot-the-900-year-old-ginkgo-tree", to: "kdrama-the-glory-go-game-filming-location-cheongju-central-park-recree" },
    { from: "crash-landing-on-you-hantangang-sky-bridge-where-se-ri-and-jeong-hyeok-confirmed-their-fated-connection", to: "kdrama-crash-landing-on-you-fated-connection-filming-location-hantangang-sky-bridge-pocheon-recree" },
    { from: "the-overpass-where-sae-ro-yi-told-yi-seo-i-need-you-in-itaewon-class", to: "kdrama-itaewon-class-i-need-you-filming-location-itaewon-overpass-yongsan-recree" },
    { from: "the-breakwater-where-gong-yoo-offered-buckwheat-flowers-jumunjin-yeongjin-beach-gangneung", to: "kdrama-goblin-buckwheat-flowers-filming-location-jumunjin-yeongjin-beach-gangneung-recree" },
    { from: "the-hackberry-tree-where-junho-gave-youngwoo-his-jacket-changwon-bukbu-ri-dangsan-tree", to: "kdrama-extraordinary-attorney-woo-junho-jacket-filming-location-bukburi-hackberry-tree-changwon-recree" },
    { from: "lovely-runner-sols-house-the-blue-gate", to: "kdrama-lovely-runner-blue-gate-umbrella-filming-location-mon-ted-cafe-yongsan-recree" },
    { from: "the-heart-tree-from-king-the-land-where-sarang-and-guwon-shot-hotel-promotional-photos-sonokam-jeju-outdoor-garden", to: "kdrama-king-the-land-heart-tree-filming-location-sonokam-jeju-seogwipo-recree" },
    { from: "what-koreans-eat-every-day-kimchi", to: "korea-food-kimchi-traditional-fermented-hansik-recree" },
    { from: "first-meal-on-jeju-island-must-try-jeju-pork-noodle-soup", to: "korea-food-jeju-meokdol-gogi-guksu-noodles-jeju-recree" },
    { from: "blackpink-official-goods-shop-the-samee-in-front-of-ygs-new-building", to: "kpop-blackpink-yg-official-goods-visited-spot-the-samee-mapo-recree" },
    { from: "the-stage-from-blackpinks-as-if-its-your-last-kyung-hee-university-international-campus", to: "kpop-blackpink-as-if-its-your-last-mv-filming-location-kyunghee-university-yongin-recree" },
    { from: "the-track-blackpink-jennie-raced-on-paju-speed-park", to: "kpop-blackpink-jennie-go-kart-filming-location-paju-speed-park-recree" },
    { from: "jisoo-and-ross-bucket-list-pottery-studio-visit", to: "kpop-blackpink-jisoo-rose-pottery-studio-filming-location-hongdae-mapo-recree" },
    { from: "seungkwans-pick-podong-pudding-the-bear-pudding-pilgrimage-site", to: "kpop-seventeen-seungkwan-podong-pudding-cafe-seoul-forest-seongdong-recree" },
    { from: "europe-in-seventeens-mv-keimyung-university-daemyung-campus", to: "kpop-seventeen-mansae-dont-wanna-cry-mv-filming-location-keimyung-university-daegu-recree" },
    { from: "seventeens-isul-live-frozen-pork-belly-mecca-daebongjip", to: "kpop-seventeen-isul-live-filming-location-daebongjip-restaurant-gangnam-recree" },
    { from: "stray-kids-walkin-on-water-filming-location", to: "kpop-stray-kids-walkin-on-water-concept-photo-location-daejanggeum-park-yongin-recree" },
    { from: "skzs-trainee-days-regular-spot-for-home-style-meals-jyp-idols-comfort-food", to: "kpop-stray-kids-trainee-regular-restaurant-cheongdam-alley-gangnam-recree" },
    { from: "skz-code-sauna-episode-experience-a-jjimjilbang-like-stray-kids", to: "kpop-stray-kids-skz-code-sauna-filming-location-bulgama-hongdae-mapo-recree" },
    { from: "twices-like-ohh-ahh-mv-the-abandoned-amusement-park", to: "kpop-twice-like-ooh-ahh-mv-filming-location-yongmaland-jungnang-recree" },
    { from: "momos-graceful-jokbal-dance-spot", to: "kpop-twice-momo-jokbal-dance-restaurant-manjok-ohyang-jung-recree" },
    { from: "goyang-stadium-the-pilgrimage-site-for-twices-cheer-up-mv-cheerleader-scene", to: "kpop-twice-cheer-up-mv-filming-location-goyang-stadium-recree" },
    { from: "aespas-dirty-work-filming-location-suncheon-castle", to: "kpop-aespa-dirty-work-mv-filming-location-castle-suncheon-recree" },
    { from: "aespas-karina-giselles-favorite-spot-silbioks-seaweed-sujebi", to: "kpop-aespa-karina-giselle-find-tour-restaurant-silbiok-seongsu-recree" },
    { from: "dive-into-the-sm-idol-universe-kwangya", to: "kpop-sm-artists-kwangya-official-goods-visited-spot-seongsu-recree" },
    { from: "nct-127-taeyong-instagram-spot-hongdae-kpop-pilgrimage", to: "kpop-nct127-taeyong-instagram-pink-hair-photo-location-hongdae-mapo-recree" },
    { from: "nct-johnnys-jump-shot-holy-ground-seoul-oil-tank-culture-park-t3-nct-127-johnny-instagram-k-pop-pilgrimage-spot", to: "kpop-nct127-johnny-instagram-jump-shot-photo-location-oil-tank-t3-mapo-recree" },
    { from: "nct-dojaejong-doyoungs-first-appearance-janggyo-beach-nct-dojaejong-the-music-film-filming-location-in-yangyang-korea-a-k-pop-pilgrimage", to: "kpop-nct-dojaejong-doyoung-music-film-filming-location-janggyo-beach-yangyang-recree" },
    { from: "geunjeongjeon-the-palace-where-nct-127-became-gods-nct-127-fact-check-mv-filming-location-gyeongbokgung-seoul-kpop-pilgrimage", to: "kpop-nct127-fact-check-mv-filming-location-geunjeongjeon-gyeongbokgung-jongno-recree" },
    { from: "nct-127-fact-check-mv-gwanghwamun-filming-location-k-pop-pilgrimage-in-seoul", to: "kpop-nct127-fact-check-mv-filming-location-gwanghwamun-jongno-recree" },
    { from: "enhypens-chuseok-hanok-home-eunpyeong-hanok-village-enhypen-en-oclock-filming-location-seoul-k-pop-pilgrimage", to: "kpop-enhypen-en-oclock-chuseok-filming-location-eunpyeong-hanok-village-recree" },
    { from: "enhypens-given-taken-debut-mv-reed-field-pilgrimage-site-eulwang-park-incheon-a-k-pop-holy-land", to: "kpop-enhypen-given-taken-debut-mv-filming-location-eulwang-park-incheon-recree" },
    { from: "enhypens-fun-at-smob-goyang-a-pilgrimage-for-engenes", to: "kpop-enhypen-en-oclock-escape-game-filming-location-smob-goyang-recree" },
    { from: "txts-neverland-farewell-bunam-beach-txt-tomorrow-x-together-temptation-farewell-concept-clip-filming-location-bunam-beach-samcheok-kpop-pilgrimage", to: "kpop-txt-temptation-farewell-concept-clip-filming-location-bunam-beach-samcheok-recree" },
    { from: "ive-blackhole-mv-filming-location-seoul-sky-lotte-world-tower-sky-bridge-k-pop-pilgrimage", to: "kpop-ive-blackhole-mv-filming-location-seoul-sky-bridge-songpa-recree" },
    { from: "red-railroad-bridge-in-ateezs-aurora-mv-ateez-aurora-mv-filming-location-bukhangang-railroad-bridge-namyangju-kpop-pilgrimage", to: "kpop-ateez-aurora-mv-filming-location-bukhangang-railroad-bridge-namyangju-recree" },
    { from: "the-pool-from-irene-seulgis-mv-baegot-hanul-park-red-velvet-irene-seulgi-monster-naughty-mv-filming-location-baegot-hanul-park-siheung-k-pop-pilgrimage", to: "kpop-red-velvet-irene-seulgi-naughty-mv-filming-location-baegot-hanul-park-siheung-recree" },
    { from: "iryeong-station-the-iconic-spot-where-bts-v-stood-in-the-spring-day-mv-bts-spring-day-mv-filming-location-in-yangju-a-k-pop-pilgrimage-site", to: "kpop-bts-v-spring-day-mv-filming-location-ilyeong-station-yangju-recree" },
    { from: "the-palace-where-sugas-daechwita-mv-was-filmed-bts-suga-agust-d-daechwita-mv-filming-location-yongin-daejanggeum-park-kpop-pilgrimage", to: "kpop-bts-suga-daechwita-mv-filming-location-daejanggeum-park-yongin-recree" },
    { from: "the-street-where-bts-danced-dynamite-everland-rocksville-bts-dynamite-americas-got-talent-performance-filming-location-everland-rocksville-kpop-pilgrimage", to: "kpop-bts-dynamite-agt-performance-filming-location-everland-rocksville-yongin-recree" },
    { from: "goblin-filming-location-gamgodang-gil-stone-wall-road-in-seoul-where-the-goblin-and-eun-tak-first-met", to: "kdrama-goblin-first-meeting-filming-location-gamgodang-gil-jongno-recree" },
    { from: "txt-hueningkais-dream-staircase-youngmun-middle-school-k-pop-pilgrimage-to-an-idol-school-in-seouls-seongbuk-gu", to: "kpop-txt-hueningkai-middle-school-visited-spot-youngmun-seongbuk-recree" },
    { from: "txt-soobins-memories-han-river-healing-cafe-txt-soobin-han-river-cafe-k-pop-pilgrimage-yongsan-gu-filming-location-urban-plant", to: "kpop-txt-soobin-han-river-cafe-visited-spot-urban-plant-yongsan-recree" },
    { from: "txts-fighting-spirit-unleashed-n-seoul-tower-game-plaza", to: "kpop-txt-fandom-tour-arcade-filming-location-n-seoul-tower-game-plaza-yongsan-recree" },
    { from: "txt-friendship-forever-n-seoul-tower-love-locks-txt-yeonjun-n-seoul-tower-love-lock-k-pop-pilgrimage-eternal-promise-seoul-landmark", to: "kpop-txt-fandom-tour-love-locks-visited-spot-n-seoul-tower-yongsan-recree" },
    { from: "k-pop-demon-hunters-lumi-jinwoos-romantic-fortress-wall-path-at-naksan-park-k-pop-demon-hunters-naksan-park-filming-location-seoul-hanyang-fortress-wall-pilgrimage", to: "kanime-kpop-demon-hunters-lumi-jinwoo-fortress-wall-filming-location-naksan-park-jongno-recree" },
    { from: "k-pop-demon-hunters-lion-boyzs-final-stage-n-seoul-tower-k-pop-demon-hunters-n-seoul-tower-filming-location-namsan-seoul-landmark-pilgrimage", to: "kanime-kpop-demon-hunters-saja-boys-final-stage-filming-location-n-seoul-tower-yongsan-recree" },
    { from: "k-pop-demon-hunters-jinwoos-400-year-past-at-geunjeongjeon-gyeongbokgung-palace-filming-location-seoul-joseon-dynasty-pilgrimage", to: "kanime-kpop-demon-hunters-jinwoo-flashback-filming-location-geunjeongjeon-gyeongbokgung-jongno-recree" },
    { from: "k-pop-demon-hunters-lumi-and-jinus-fight-and-song-location-k-pop-demon-hunters-bukchon-hanok-village-filming-location-seoul-traditional-pilgrimage", to: "kanime-kpop-demon-hunters-lumi-jinu-fight-song-filming-location-bukchon-hanok-village-jongno-recree" },
    { from: "the-soul-food-of-koreans-nostalgic-tteokbokki", to: "korea-food-tteokbokki-korean-street-food-hansik-recree" },
    { from: "gwangjang-market-essential-yukhoe-bindaetteok-hotspot", to: "korea-food-seoul-gwangjang-market-yukhoe-bindaetteok-restaurant-hansik-jongno-recree" },
    { from: "sutjang-where-seventeen-gathered-for-a-group-dinner-in-yongsan", to: "kpop-seventeen-group-dinner-restaurant-sutjang-yongsan-recree" },
    { from: "the-malt-cream-latte-illit-minju-drank-twice-in-one-day-a-mocha-bun-cafe", to: "kpop-illit-minju-malt-cream-latte-cafe-standard-bun-yongsan-recree" },
    { from: "jeukseok-tteokbokki-spot-run-by-an-army-in-yongsan", to: "kpop-bts-army-jeukseok-tteokbokki-restaurant-street-food-yongsan-recree" },
    { from: "the-charcoal-bbq-spot-from-cortiss-music-video", to: "kpop-cortis-music-video-redred-filming-location-kbbq-restaurant-gimpo-recree" },
    { from: "bts-vs-pick-winter-bungeoppang-hotspot", to: "kpop-bts-v-winter-bungeoppang-street-food-hannam-yongsan-recree" },
    { from: "the-forest-villa-where-bts-healed-in-the-soop-bts-pyeongchang-filming-location-bts-in-the-soop-season-2-pyeongchang-filming-location-gangwon-pilgrimage", to: "kpop-bts-in-the-soop-season-2-filming-location-forest-villa-pyeongchang-recree" },
    { from: "skz-eats-ramyeon-and-plays-badminton-jamsil-han-river-park-stray-kids-skzskz-han-river-picnic-filming-location-seoul-jamsil-pilgrimage", to: "kpop-stray-kids-skzskz-han-river-picnic-filming-location-jamsil-hangang-park-songpa-recree" },
    { from: "be-like-skz-lee-know-felix-cheongnyeondabang-tteokbokki-stray-kids-skzskz-tteokbokki-restaurant-lee-know-felix-filming-location-seoul-pilgrimage-spot", to: "kpop-stray-kids-lee-know-felix-skzskz-tteokbokki-restaurant-cheongnyeondabang-recree" },
    { from: "saetbyeol-childrens-park-visited-by-lee-know-and-felix-stray-kids-skzskz-park-lee-know-felix-filming-location-seoul-seongdong-pilgrimage", to: "kpop-stray-kids-lee-know-felix-skzskz-hellevator-practice-visited-spot-saetbyeol-park-seongdong-recree" },
  ];