name: "Bug Report"
description: "버그 제보"
labels: ["fix"]
body:
  - type: input
    id: title-guide
    attributes:
      label: "제목 양식"
      description: "이슈 제목을 `fix: 버그 내용` 형식으로 작성해주세요"
      placeholder: "예: fix: 포스트 스크랩 시 404 에러"
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: "버그 설명"
      description: "무엇이 잘못되고 있나요?"
      placeholder: "기대 동작과 실제 동작을 설명해주세요"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "재현 방법"
      description: "버그를 재현하는 단계"
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "스크린샷 / 에러 로그"
      description: "있으면 첨부해주세요"
      placeholder: "선택사항입니다"
    validations:
      required: false
