name: "Feature Request"
description: "새로운 기능 개발"
labels: ["feature"]
body:
  - type: input
    id: title-guide
    attributes:
      label: "제목 양식"
      description: "이슈 제목을 `feat: 작업 내용` 형식으로 작성해주세요"
      placeholder: "예: feat: Post 상세 페이지 구현"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "작업 내용"
      description: "무엇을 만들어야 하나요?"
      placeholder: "어떤 기능을 구현하는지 간단히 설명해주세요"
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "세부 작업"
      description: "구현할 항목들을 체크리스트로 작성해주세요"
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "참고 사항"
      description: "디자인 시안, 관련 이슈, API 명세 등"
      placeholder: "선택사항입니다"
    validations:
      required: false
