ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isShop" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isAffiliate" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "purchaseUrl" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "subtitle" TEXT;
